// Generated by Selenium IDE
//Serkan Koçoğlu 17070006004
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;

public class EmailTest {

    public void email(WebDriver driver) {
        driver.get("https://discord.com/");
        driver.manage().window().setSize(new Dimension(1051, 806));
        driver.findElement(By.linkText("Giriş")).click();
        driver.findElement(By.cssSelector(".smallRegisterLink-2LCrMe > .contents-18-Yxp")).click();
        driver.findElement(By.name("username")).sendKeys("LifeGuard");
        driver.findElement(By.name("password")).sendKeys("Serkan35");
        driver.findElement(By.name("password")).sendKeys(Keys.ENTER);

        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("||||||||||**@gmail.com"); //Program Error !!
        driver.findElement(By.name("email")).sendKeys(Keys.ENTER);


        // Enters to system by upper code segment
      /*  driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("12345677864249@gmail.com"); //Program Error !!
        driver.findElement(By.name("email")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("NON-ex1stentmail@gmail.com"); // Program Error !!
        driver.findElement(By.name("email")).sendKeys(Keys.ENTER);
*/
    }

    public static void main(String[] args) {

        System.setProperty("webdriver.chrome.driver", "C:\\Users\\serka\\Desktop\\chromedriver.exe");
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--whitelisted-ips=''");
        WebDriver driver = new ChromeDriver(options);

        EmailTest e = new EmailTest();
        e.email(driver);
    }
}