// Generated by Selenium IDE
//Serkan Koçoğlu 17070006004
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class PasswordTest {
    public void password(WebDriver driver) {

        driver.get("https://discord.com/");
        driver.manage().window().setSize(new Dimension(1051, 806));
        driver.findElement(By.linkText("Giriş")).click();

        WebDriverWait waitRegisterPage = new WebDriverWait(driver, 15); //To Go Registration Page With a Sublink !
        waitRegisterPage.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".smallRegisterLink-2LCrMe > .contents-18-Yxp"))).click();

        driver.findElement(By.name("email")).sendKeys("nonexistentmail5@gmail.com");
        driver.findElement(By.name("username")).sendKeys("LifeGuard");
        driver.findElement(By.name("password")).sendKeys(Keys.ENTER); //Empty Password field

        driver.findElement(By.name("password")).sendKeys("aaaaaa");
        driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("password")).clear();

        driver.findElement(By.name("password")).sendKeys("short");
        driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("password")).clear();
        driver.findElement(By.name("password")).clear();
        // I have added these doubled 'clear()'s because program runs so fast and
        // are not able to order and fills as "short123abc" but this provides earning time
        //this worked but I'm curious about the real solution !

        driver.findElement(By.name("password")).sendKeys("123abc");
        driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.name("password")).clear();
        driver.findElement(By.name("password")).clear();

        driver.findElement(By.name("password")).sendKeys("     1 2  ");
        driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    }

    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\serka\\Desktop\\chromedriver.exe");
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--whitelisted-ips=''");
        WebDriver driver = new ChromeDriver(options);

        PasswordTest pt = new PasswordTest();
        pt.password(driver);
    }
}
